extends:
  - eslint:recommended
  - plugin:react/recommended
settings:
  react:
    version: '16.3'
env:
  browser: true
  es6: true
  node: true
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    modules: true
