extends:
  - eslint:recommended
  - plugin:flowtype/recommended
  - plugin:react/recommended
plugins:
  - flowtype
env:
  browser: true
  es6: true
  node: true
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true
